# volumen para persistencia 
volumes:
  data_taller3:
    name: db_postgres

# redes aisladas para seguridad
networks:
  network_sist:
    driver: bridge
  db_network:
    driver: bridge

# servicios
services:
  #nginx:
    
  #  build:
  #    context: ./nginx
  #    dockerfile: dockerfile
  #  container_name: nginx_container
  #  ports:
  #    - 80:8080
  #  networks:
  #    - network_sist
  #  depends_on:
  #    - frontend
  #    - backend

  frontend:
    build:
      context: ./frontend/votos
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - 3000:3000
    networks:
      - network_sist

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8080:8080
    #deploy:
    #  replicas: 1
    environment:
      - DB_HOST=db_postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - network_sist
      - db_network
    depends_on:
      - db_postgres

  db_postgres:
      image: postgres:15-alpine
      container_name: bd_elecciones
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - data_taller3:/var/lib/postgresql/data # Persistencia de Datos
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
       - db_network



