version: '3.8'
# volumen para persistencia 
volumes:
  postgres_data:
    name: db_postegres

# redes aisladas para seguridad
networks:
  network_sist:
    driver: bridge
  db_network:
    driver: bridge

# servicios
services:
  #nginx:
    
  #  build:
  #    context: ./nginx
  #    dockerfile: dockerfile
  #  container_name: nginx_container
  #  ports:
  #    - 80:8080
  #  networks:
  #    - network_sist
  #  depends_on:
  #    - frontend
  #    - backend

  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: dockerfile
  #  container_name: frontend_container
  #  networks:
  #    - network_sist

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8080:8080
    #deploy:
    #  replicas: 2
    #environment:
    #  - DB_HOST=DB
    #  - DB_USER=${DB_USER}
    #  - DB_PASSWORD=${DB_PASSWORD}
    #  - DB_NAME=${DB_NAME}
    networks:
      - network_sist
      #- db_network
    #depends_on:
    #  - DB

  #DB:
  #  image: postgres:alpine
  #  container_name: db_test
  #  environment:
  #    - POSTGRES_USER=${DB_USER}
  #    - POSTGRES_PASSWORD=${DB_PASSWORD}
  #    - POSTGRES_DB=${DB_NAME}
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  networks:
  #    - db_network




#Declaracion del volumen
volumes:
  data_taller3: