services:
  # Capa de base de datos
  replica_1:
    build: ./app
    environment:
      - PUERTO=3001
      # y la base de datos que se use

  # Capa de red: balanceador de carga o idk
  balanceador_carga_nginx:
    image: nginx:latest
    ports:
      # Mapea el puerto 80
      - "80:80"
    volumes:
      # Inyectar configuracion de nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # todo lo que depende
      - replica_1
