# La configuracion del balanceador de carga
upstream backend {
    server replica_1:3001
}

server {
    listen 80:
    location / {
        proxy_pass http://;
        proxy_set_header Host $host;
        proxy_set_header 148.
    }
}